# Generated by Django 4.2.8 on 2023-12-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_klient', models.CharField(max_length=32)),
                ('telefon_klient', models.CharField(max_length=32)),
                ('email_klient', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_gadget', models.CharField(blank=True, max_length=32, null=True)),
                ('model_gadget', models.CharField(max_length=32)),
                ('brand_gadget', models.CharField(max_length=32)),
                ('type_gadget', models.CharField(max_length=32)),
                ('password_gadget', models.CharField(blank=True, max_length=32, null=True)),
                ('opis_problem', models.TextField(blank=True, null=True)),
                ('zestaw', models.CharField(blank=True, max_length=64, null=True)),
                ('pilne', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('master_gadgets', models.ForeignKey(on_delete=django.db.models.deletion.SET_DEFAULT, to='gadgets.klient')),
            ],
        ),
    ]
