# Generated by Django 4.2.8 on 2023-12-25 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gadget',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='gadget',
            name='master_gadget',
            field=models.CharField(default='TPL', max_length=32),
        ),
        migrations.AddField(
            model_name='gadget',
            name='telefon_master_gadget',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='klient',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
