# Generated by Django 4.2.8 on 2023-12-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='in_serwis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gadget',
            name='location',
            field=models.CharField(default='STOKŁOSY', max_length=32),
        ),
        migrations.AddField(
            model_name='gadget',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gadget',
            name='time_in_serwis',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='status',
            field=models.CharField(blank=True, db_index=True, default='NOWY', max_length=32, null=True),
        ),
    ]
