# Generated by Django 4.2.8 on 2023-12-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0002_gadget_in_serwis_gadget_location_gadget_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
