# Generated by Django 4.2.8 on 2023-12-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0002_alter_gadget_options_alter_klient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='brand_gadget',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='master_gadget',
            field=models.CharField(db_index=True, default='TPL', max_length=32),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='model_gadget',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='pilne',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='serial_gadget',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='telefon_master_gadget',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='type_gadget',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='klient',
            name='name_klient',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telefon_klient',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
