# Generated by Django 4.2.8 on 2023-12-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0003_alter_gadget_brand_gadget_alter_gadget_master_gadget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='master_gadget',
            field=models.CharField(db_index=True, default='TPL', max_length=64),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='password_gadget',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='pilne',
            field=models.CharField(blank=True, db_index=True, default='NO', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='status',
            field=models.CharField(blank=True, db_index=True, default='NEW', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='email_klient',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='name_klient',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
