# Generated by Django 4.2.8 on 2023-12-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0004_alter_gadget_master_gadget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='type_gadget',
            field=models.CharField(db_index=True, default='Laptop', max_length=32),
        ),
    ]
