# Generated by Django 4.2.8 on 2024-01-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0008_alter_gadget_in_serwis_alter_gadget_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetingsCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_gadget', models.CharField(blank=True, max_length=16, null=True)),
                ('filter_klient', models.CharField(blank=True, max_length=16, null=True)),
                ('filter_dashboar', models.CharField(blank=True, max_length=16, null=True)),
                ('filter_work', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
