# Generated by Django 4.2.8 on 2024-01-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0010_alter_setingscrm_filter_dashboar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Klient',
        ),
    ]
