# Generated by Django 4.2.8 on 2024-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='in_serwis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='kasa_klient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='klient',
            name='opis_klient',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='types_klient',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
