# Generated by Django 4.2.8 on 2024-01-27 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('klienty', '0002_klient_in_serwis_klient_kasa_klient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='in_serwis',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='kasa_klient',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telefon_klient',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
