# Generated by Django 4.2.8 on 2024-01-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klienty', '0003_alter_klient_created_at_alter_klient_in_serwis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klient',
            options={'ordering': ('-id',)},
        ),
    ]
