# Generated by Django 4.2.8 on 2024-02-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServisLocationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servis_name', models.CharField(blank=True, max_length=32, null=True)),
                ('servis_location', models.CharField(max_length=32)),
                ('servis_adress', models.CharField(blank=True, max_length=512, null=True)),
                ('servis_telephone', models.CharField(blank=True, max_length=32, null=True)),
                ('servis_email', models.CharField(blank=True, max_length=32, null=True)),
                ('servis_opis', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
