# Generated by Django 4.2.8 on 2024-01-06 15:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gadgets', '0001_initial'),
        ('klienty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.CharField(default='MANAGER', max_length=32)),
                ('gadget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadgets.gadget')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienty.klient')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
