# Generated by Django 4.2.8 on 2024-01-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klienty', '0001_initial'),
        ('gadgets', '0002_alter_gadget_klient'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='gadget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gadgets.gadget'),
        ),
        migrations.AlterField(
            model_name='note',
            name='klient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klienty.klient'),
        ),
    ]
