# Generated by Django 4.2.8 on 2024-01-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_gadget_alter_note_klient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.CharField(default='Andrej Khairov', max_length=32),
        ),
    ]
