# Generated by Django 4.2.8 on 2024-02-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='read',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
