# Generated by Django 4.2.8 on 2024-01-06 15:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klienty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetingsCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_gadget', models.CharField(blank=True, default='WSZYSCY', max_length=16, null=True)),
                ('filter_klient', models.CharField(blank=True, default='WSZYSCY', max_length=16, null=True)),
                ('filter_dashboar', models.CharField(blank=True, default='WSZYSCY', max_length=16, null=True)),
                ('filter_work', models.CharField(blank=True, default='WSZYSCY', max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_gadget', models.CharField(db_index=True, default='TPL', max_length=64)),
                ('telefon_master_gadget', models.CharField(db_index=True, max_length=32)),
                ('serial_gadget', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('model_gadget', models.CharField(db_index=True, max_length=32)),
                ('brand_gadget', models.CharField(db_index=True, max_length=32)),
                ('type_gadget', models.CharField(db_index=True, max_length=32)),
                ('password_gadget', models.CharField(blank=True, max_length=64, null=True)),
                ('opis_problem', models.TextField(blank=True, null=True)),
                ('zestaw', models.CharField(blank=True, max_length=64, null=True)),
                ('pilne', models.CharField(blank=True, db_index=True, default='NO', max_length=32, null=True)),
                ('status', models.CharField(blank=True, db_index=True, default='NOWY', max_length=32, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(db_index=True, default='STOKŁOSY', max_length=32)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('in_serwis', models.BooleanField(db_index=True, default=True)),
                ('time_in_serwis', models.DurationField(blank=True, null=True)),
                ('opis_naprawy', models.TextField(blank=True, null=True)),
                ('type_service', models.CharField(default='PŁATNE', max_length=32)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klienty.klient')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
