# Generated by Django 4.2.8 on 2024-01-06 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klienty', '0001_initial'),
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='klient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='klienty.klient'),
        ),
    ]
