# Generated by Django 4.2.8 on 2024-01-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klienty', '0001_initial'),
        ('gadgets', '0002_alter_gadget_klient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='klient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='klienty.klient'),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='pilne',
            field=models.CharField(blank=True, db_index=True, default='NIE', max_length=32, null=True),
        ),
    ]
