# Generated by Django 4.2.8 on 2024-01-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klienty', '0001_initial'),
        ('gadgets', '0003_alter_gadget_klient_alter_gadget_pilne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='klient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='klienty.klient'),
        ),
    ]
