# Generated by Django 4.2.8 on 2023-12-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0003_alter_gadget_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='opis_naprawy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
