# Generated by Django 4.2.8 on 2024-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0004_alter_gadget_klient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='opis_naprawy',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
