# Generated by Django 4.2.8 on 2024-01-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0006_gadget_type_service_alter_gadget_opis_naprawy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='type_service',
            field=models.TextField(default='PŁATNE'),
        ),
    ]
