# Generated by Django 4.2.8 on 2024-01-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0006_remove_gadget_master_gadget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='brand_gadget',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='in_serwis',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='location',
            field=models.CharField(blank=True, db_index=True, default='STOKŁOSY', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='model_gadget',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='type_gadget',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='type_service',
            field=models.CharField(blank=True, default='PŁATNE', max_length=32, null=True),
        ),
    ]
