# Generated by Django 4.2.8 on 2024-01-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0007_alter_gadget_type_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='in_serwis',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='location',
            field=models.CharField(db_index=True, default='STOKŁOSY', max_length=32),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='type_service',
            field=models.CharField(default='PŁATNE', max_length=32),
        ),
    ]
