# Generated by Django 4.2.8 on 2024-01-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0007_alter_gadget_brand_gadget_alter_gadget_in_serwis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='technik_ost',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
