# Generated by Django 4.2.8 on 2024-03-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0009_setingscrm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='usterki_zewn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='setingscrm',
            name='filter_dashboar',
            field=models.CharField(blank=True, default='STOKŁOSY', max_length=16, null=True),
        ),
    ]
