# Generated by Django 4.2.8 on 2024-01-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0009_setingscrm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setingscrm',
            name='filter_dashboar',
            field=models.CharField(blank=True, default='WSZYSCY', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='setingscrm',
            name='filter_gadget',
            field=models.CharField(blank=True, default='WSZYSCY', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='setingscrm',
            name='filter_klient',
            field=models.CharField(blank=True, default='WSZYSCY', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='setingscrm',
            name='filter_work',
            field=models.CharField(blank=True, default='WSZYSCY', max_length=16, null=True),
        ),
    ]
