# Generated by Django 4.2.8 on 2024-03-24 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0010_gadget_usterki_zewn_alter_setingscrm_filter_dashboar'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='managed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
