# Generated by Django 4.2.8 on 2024-04-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0012_gadget_alarm_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='setingscrm',
            name='filter_manager',
            field=models.CharField(blank=True, default='WSZYSCY', max_length=16, null=True),
        ),
    ]
