# Generated by Django 4.2.8 on 2024-04-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0013_setingscrm_filter_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='alarm_on',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
