# Generated by Django 4.2.8 on 2024-04-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0014_gadget_alarm_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='setingscrm',
            name='filter_manager_czeka_na_części',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='setingscrm',
            name='filter_manager_czeka_na_zgode',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='setingscrm',
            name='filter_manager_diagnostyka',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='setingscrm',
            name='filter_manager_gotowy',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='setingscrm',
            name='filter_manager_naprawienie',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='setingscrm',
            name='filter_manager_nowy',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='setingscrm',
            name='filter_manager_rezygnacja',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='setingscrm',
            name='filter_manager_wycena',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='setingscrm',
            name='filter_manager_zaliczka',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
