# Generated by Django 4.2.8 on 2024-04-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0015_setingscrm_filter_manager_czeka_na_części_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setingscrm',
            name='filter_manager',
            field=models.CharField(blank=True, default='CAŁY CZAS', max_length=16, null=True),
        ),
    ]
