# Generated by Django 4.2.8 on 2024-04-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0016_alter_setingscrm_filter_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setingscrm',
            name='filter_manager',
            field=models.CharField(blank=True, default='WSZYSCY', max_length=16, null=True),
        ),
    ]
