# Generated by Django 4.2.8 on 2024-04-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0017_alter_setingscrm_filter_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='setingscrm',
            name='filter_manager_all',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='setingscrm',
            name='filter_manager',
            field=models.CharField(blank=True, default='CAŁY CZAS', max_length=16, null=True),
        ),
    ]
