# Generated by Django 4.2.8 on 2024-01-08 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0002_alter_gadget_klient'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='status',
            field=models.CharField(blank=True, default='W_PRACE', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='added_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workers',
            name='gadget',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gadgets.gadget'),
        ),
    ]
