# Generated by Django 4.2.8 on 2024-02-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_kartkarezygnacja_kartkareklamacja_kartkaplatne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='status',
        ),
        migrations.AddField(
            model_name='workers',
            name='in_work',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
