# Generated by Django 4.2.8 on 2024-02-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_remove_workers_status_workers_in_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartkarezygnacja',
            name='qnt',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
